# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180520_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Shop Subscriber', 'verbose_name_plural': 'Shop Subscribers'},
        ),
    ]
