# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180524_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
