# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_children',
            field=models.BooleanField(default=False),
        ),
    ]
