# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181121_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Nice to meet you :)', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='Nice to meet you :)', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default='Nice to meet you :)', null=True, verbose_name='description'),
        ),
    ]
