# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181122_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=':)', max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default=':)', max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, default=':)', max_length=128, null=True, verbose_name='name'),
        ),
    ]
