# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 18:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20181118_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number should be entered in the format: '+38099.......'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact phone number'),
        ),
    ]
